### ISSUE TITLE
--host=0.0.0.0 not usable across network

### ISSUE THREAD

**Issue by p-salido** [wking-io/elm-live#112]
I am running elm-live on a server and accessing the result from a laptop. In order to do this I used `--host=0.0.0.0`. However, in the rendered HTML I then see:

<pre>
<script type="text/javascript" src="//0.0.0.0:35729/livereload.js?snipver=1" async="" defer="">
</pre>

This does not work since `0.0.0.0` on the laptop I assume refers to the laptop itself, but it needs to point to the server where elm-live is running.

**Comment by tomekwi** [comment]
Hey @p-salido, thanks for reporting this! Sorry for the delay in getting back to you.

Up till now I’ve treated elm-live purely as a development server – never suspected people would want to run it on a server. Is this just a multi-machine development setup that you’ve described? Or is it a server setup that you want to open up for public access?

**Comment by p-salido** [comment]
@tomekwi I have a development server on a different machine from the laptop I use for interactive work.

**Comment by tomekwi** [comment]
OK got it @p-salido – makes sense. Does your server have an IP address that you can specify instead? I remember working on a similar setup before between my development machine and a phone on the same network. The way I managed to set things up was to use a static internal IP address of my development machine as the `--host`.

**Comment by p-salido** [comment]
@tomekwi IP address is a workaround that works across the network, however the server maps its own hostname to 127.0.0.1 in the hosts file as is standard practice hence e.g. `curl http://server/...` from the server itself does not work, as the application listens on the network IP but not on loopback.

**Comment by tomekwi** [comment]
Oh right, I see. Do you have an idea how to solve this?

Unfortunately the LiveReload script is served from a different port by [budo](https://github.com/mattdesl/budo) – the server that we use under the hood. I looked into the possibility of referencing the port kinda relatively, without specifying the host. Turns out there’s no straightforward solution: https://stackoverflow.com/questions/6016120/relative-url-to-a-different-port-number-in-a-hyperlink.

Before we set out on covering this use case (we’d probably need to make some noise upstream in the budo repo), I’m still thinking if your problem could be addressed differently. Have you thought of setting up a new record in your `/etc/hosts` which points at the server’s IP both on your server (`myapp.local 127.0.0.1`) and on your laptop (`myapp.local <the IP address of your server as reachable from your laptop>`)?

You could then start elm-live with `--host=myapp.local` and have your app accessible at http://myapp.local.

Think it makes sense?

**Comment by p-salido** [comment]
I believe webpack uses two ports in a similar fashion, perhaps looking at how it works can be instructive.

The most sensible way to go I can presently think of is to look at the value of http Host header and use the same host specified there. If no Host header is specified then use the listen address as currently happens.

**Comment by wking-io** [comment]
Just updated to 0.19 version of plugin that should fix this issue. If that is not the case please open a new issue! :)
