### ISSUE TITLE
Before/after build events that change elm files cause a second build

### ISSUE THREAD

**Issue by bstanley78** [wking-io/elm-live#115]
I'm using **elm-format** as a before-build event, but the watcher picks up its changes and immediately kicks off a second build right as the first one finishes.

Does functionality currently exist to pause the watcher during the before/after events?

**Comment by architectcodes** [comment]
Hey @bstanley78, thanks for asking! It’s not possible right now. Just out of curiosity: why are you running elm-format as a before-build event rather than using an editor integration and/or a pre-commit hook?

BTW, I’m really sorry for the super late reply. There’s a ton of things going on in my life right now: alongside a super intensive full time job I’m also building a [new business](https://homalive.com). Not to mention [my lovely little family](https://instagram.com/weloveeachotherlikemad) that deserves my time more than anything else 👨‍👩‍👦‍👦

I’ll be looking for new maintainers of elm-live – so if you know anyone that’s keen to take over the project, let me know! 👩‍🚀

**Comment by wking-io** [comment]
Haven't heard back about this issue in a while. If still an issue please open a new one and we will get this knocked out!
