### ISSUE TITLE
web sockets?

### ISSUE THREAD

**Issue by jligeza** [wking-io/elm-live#151]
I need to proxy both http (for ajax) and ws. The ws might have different proxy prefix. How can I do this?

**Comment by wking-io** [comment]
Currently you can't. The server elm-live uses is `elm-serve` and it only supports a single proxyPrefix. 

If you have any experience with doing this on a Node server you can hop over to https://github.com/wking-io/elm-serve and see if you can make a PR to add it. Otherwise feel free to add an issue over on that repo. 😊
