### ISSUE TITLE
Error In Command - Output In Wrong Location

### ISSUE THREAD

**Issue by AndrewEdgar** [wking-io/elm-live#206]
Hello,

I'm following the "Beginning Elm" tutorial and ran into an elm-live command error during this chapter [https://elmprogramming.com/saving-app-state.html](https://elmprogramming.com/saving-app-state.html) 

The error was as follows:

`elm-live post-app/Main.elm --pushstate -- --output=elm.js

Usage: <elm-main> [options] [--] [elm make options]

-- Output In Wrong Location -----------------

You have used the elm make flag --output in the wrong location. As seen in the usage example about, all elm make flags must be added to your command after the -- separator.`

Am I missing something here?

**Comment by brynlewis** [comment]
I have the same issue. If I run the example in the --output command:

$ elm-live src/HomePage.elm -- --output=elm.js

I get the same error:

----------------------
|| ERROR IN COMMAND ||
----------------------


Usage: <elm-main> [options] [--] [elm make options]

-- Output In Wrong Location -----------------

Also, why is the usage citing <elm-main> ?

**Comment by jonsa** [comment]
You get this error because you're running the command in `PowerShell`. You need to qoute the double dash by either `'--'`, `"--"` or `` `--``. You will get an [`Error 'console' is undefined`](https://osric.com/chris/accidental-developer/2016/06/node-js-error-console-is-undefined/) but it can be ignored.

My suggestion is to either run the command using `cmd` if you want a stand-alone terminal or create a `package.json` file with
```json
{
    "scripts": {
        "start": "elm-live post-app/Main.elm --pushstate -- --output=elm.js"
    }
}
```
and start the dev-server with `npm start` if you want to use `PowerShell` or the terminal in `VSCode`

**Comment by wking-io** [comment]
Thanks for the info @jonsa. That will be the fix for anyone looking into this issue.

**Comment by petesantos** [comment]
I am seeing this issue as well and am not using powershell. I tried adding quotes, but that did not solve the issue. Any help would be appreciated!

**Comment by prescottbreeden** [comment]
If you are running a unix shell, I've only gotten it to work by doubling the dashes:

`yarn elm-live src/Main.elm -- -- --output=main.js`

nice little variety to off-by-one bugs :)
