### ISSUE TITLE
Browsersync / HMR

### ISSUE THREAD

**Issue by erlandsona** [wking-io/elm-live#75]
I ❤️ elm-live! I was seriously struggling with a webpack config before I found this and it has greatly simplified my workflow.

That said, I found in the ether of githubz, there's another tool called [elm-server](https://github.com/maxgurewitz/elm-server) which is a similar approach to the elm-live setup only it uses browsersync.

Granted, it doesn't have you're before-build hook so it won't compile elm-css.

I notice this repo is a bit more active / well maintained and I figured you'd be the better one to suggest integrating browsersync.

Also is there a way to integrate with some of the hot-module-replacement / hot-reload tools that others have made?

What are some good ways to do that?

**Comment by tomekwi** [comment]
Hey Austin, many thanks for the kind words! I’m really glad you like it.

Just a quick note to let you know I’m aware of your question, but don’t know the exact answer yet. Hot reloading is a very interesting topic, but it looks like Elm 0.18 will really change the game in that matter. More about that in the elm-conf keynote by Evan – definitely worth watching if you haven’t already! [youtu.be/DSjbTC-hvqQ](https://youtu.be/DSjbTC-hvqQ)

I think it’s most reasonable to wait for those changes, otherwise we’d probably end up rewriting all this very soon.

Considering browsersync, here at elm-live we strongly believe in the power of community. I don’t have loads of spare time myself nowadays – so if you need the feature to land quickly, you’ll be very welcome to help. I’m always there to answer any questions 🙂.

**Comment by nqthqn** [comment]
@architectcodes think we will see movement in this direction post 0.19 release? It's helpful for new users who like to guess and check during development and don't want to recover a bunch of state to see if changes they made in the code worked.

<3 Love the tool, btw.

**Comment by architectcodes** [comment]
Thanks for the kind and encouraging words @nqthqn! I’ve been eyeing the movements towards 0.19 but couldn’t do too much to adapt elm-live to it because of the zillions of things happening in my life right now. (Super intensive startup job + building [a new business](https://homalive.com/) after hours + not to mention [my lovely little family](https://instagram.com/weloveeachotherlikemad) that deserves my time more than anything else! 👨‍👩‍👦‍👦 )

BTW, I’ll be looking for new maintainers of elm-live so we can keep the tool simple and zero config for the 0.19 release and onwards. Do you know anyone who would like to get involved and perhaps take over the project?

**Comment by wking-io** [comment]
Closing this PR due to lack of feedback from OP. If there is still an issue you want resolved open a new PR and we will figure it out!
